# Generated by Django 4.0 on 2022-10-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_name', models.TextField()),
                ('surah_uid', models.TextField()),
                ('surah_name_2', models.TextField()),
                ('surah_type', models.TextField()),
                ('number_of_ayahs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('number', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.surah')),
            ],
        ),
    ]
