# Generated by Django 4.0 on 2022-10-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='audio',
            field=models.TextField(default=''),
        ),
    ]
