# Generated by Django 4.0 on 2023-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ayah_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surah',
            name='number_of_ayahs',
            field=models.IntegerField(),
        ),
    ]
